# docker-compose.yml

version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    depends_on:
      - frontend
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
